# Exercise 7
## Céline Budding && Dorothea Müller 

In [1]:
import numpy as np
import matplotlib as mlp
import matplotlib.pyplot as plt

%matplotlib inline

## 1. The 10-armed bandit

### 1.

In [17]:
reward_prob = np.random.uniform(0, 0.9, 10)
reward_prob

array([0.56492236, 0.05582511, 0.55027567, 0.23218379, 0.71429456,
       0.81072618, 0.03613416, 0.61580318, 0.26037362, 0.09058056])

### 2.

In [ ]:
def generate_reward(reward_prob, lever_numbers):
    rewards = np.zeros(len(lever_numbers))
    for i, lever_number in enumerate(lever_numbers):
        if np.random.random() > reward_prob[lever_number]:
            rewards[i] = 0
        else:
            rewards[i] = 1
    return rewards

In [25]:
# Testing.
n = 10000
received_rewards = np.zeros(len(rewards))
for i in range(n):
    received_rewards += generate_reward(reward_prob, np.arange(0, 10))
received_rewards/=n

In [26]:
received_rewards

array([0.5662, 0.0561, 0.5476, 0.2338, 0.7101, 0.8116, 0.0343, 0.6282,
       0.2625, 0.0967])

### 3.

In [31]:
def update_q(reward_prob, q, eta = 0.01):
    delta_q = eta * (generate_reward(reward_prob, np.arange(0, len(reward_prob))) - q)
    q = q + delta_q
    return q

In [32]:
q = np.zeros(len(reward_prob))
q

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
for i in range(n):
    q = update_q(reward_prob, q)
q

array([0.56797845, 0.06620409, 0.57264853, 0.21100882, 0.70606674,
       0.81270838, 0.02610116, 0.63362152, 0.26324274, 0.06322502])

### 4.

In [36]:
def eps_greedy(q, eps):
    """Return lever(s) to be pressed, q value of chosen lever, largest q value."""
    if np.random.random() < 1-eps:
        pos = np.argmax(q)
        val = q[pos]
        largest_val = val
    else:
        pos = np.random.randint(0, len(q))
        val = q[pos]
        largest_val = q[np.argmax(q)]
        
    return [pos, val, largest_val]

### 5.